<script lang="ts"></script>

{#snippet check(text: string)}
	<li class="flex items-start gap-2.5 text-[13px] leading-6 text-slate-600"><span class="mt-1 flex size-4 shrink-0 items-center justify-center rounded-full bg-brand-50 text-brand-600"><svg class="size-2.5" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m4 10.5 4 4 8-9" /></svg></span><span>{text}</span></li>
{/snippet}

<section id="product" class="scroll-mt-24 border-b border-slate-100 bg-[#f8faff]">
	<div class="mx-auto max-w-[1240px] px-4 py-20 sm:px-6 lg:px-10 lg:py-28">
		<div class="mx-auto max-w-3xl text-center"><p class="eyebrow">Product infrastructure</p><h2 class="section-title">Simple on the surface. Serious underneath.</h2><p class="section-copy mx-auto">Connect keeps customer communication attached to the operational work it creates.</p></div>

		<div class="mt-14 grid items-center gap-10 lg:grid-cols-[0.82fr_1.18fr] lg:gap-16">
			<div><span class="feature-number">01 · WhatsApp infrastructure</span><h3 class="feature-title">Turn one WhatsApp number into a business workspace.</h3><p class="feature-copy">Use your own number while giving every teammate controlled, accountable access to the conversations they should handle.</p><ul class="mt-6 grid gap-x-5 gap-y-1 sm:grid-cols-2 lg:grid-cols-1">{@render check("Client's own WhatsApp Business number")}{@render check('Shared inbox, assignment and presence')}{@render check('Private and assigned-only conversations')}{@render check('Approved template notifications')}{@render check('Customer conversation history')}{@render check('Granular staff permissions')}</ul></div>
			<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_24px_65px_rgba(50,58,70,0.10)]">
				<div class="flex items-center justify-between border-b border-slate-200 px-4 py-3"><div><div class="text-[12px] font-semibold text-slate-800">Asha M.</div><div class="text-[9px] text-slate-400">WhatsApp · Active conversation</div></div><span class="rounded-full bg-brand-50 px-2.5 py-1 text-[9px] font-semibold text-brand-600">Assigned to Robert</span></div>
				<div class="grid min-h-[330px] sm:grid-cols-[155px_1fr]"><div class="hidden border-r border-slate-200 bg-slate-50/70 p-3 sm:block"><p class="text-[8px] font-bold text-slate-400 uppercase">Conversations</p><div class="mt-3 rounded-lg bg-white p-2.5 shadow-sm"><div class="text-[10px] font-semibold text-slate-700">Asha M.</div><div class="mt-1 truncate text-[9px] text-slate-400">Hello, do you still…</div></div><div class="mt-2 rounded-lg p-2.5 text-[9px] text-slate-400">Mariam K.</div></div><div class="p-5"><div class="max-w-[85%] rounded-xl rounded-tl-sm bg-slate-100 px-3 py-2.5 text-[11px] leading-5 text-slate-700">Hello, do you still have availability for Saturday?</div><div class="mt-5 flex flex-wrap gap-2"><span class="rounded-full bg-success/10 px-2.5 py-1 text-[9px] font-medium text-success">● Robert is typing…</span><span class="rounded-full bg-purple/10 px-2.5 py-1 text-[9px] font-medium text-purple">Neema is viewing</span></div><div class="mt-7 flex flex-wrap gap-2"><button class="rounded-lg bg-brand-500 px-3 py-2 text-[10px] font-semibold text-white">Take conversation</button><button class="rounded-lg border border-slate-200 px-3 py-2 text-[10px] font-semibold text-slate-600">Assign</button></div><div class="mt-6 border-t border-slate-100 pt-4"><p class="text-[8px] font-bold tracking-wider text-slate-400 uppercase">Visibility</p><div class="mt-2 flex flex-wrap gap-2"><span class="rounded-full bg-slate-100 px-2 py-1 text-[9px] text-slate-500">Assigned team only</span><span class="rounded-full bg-slate-100 px-2 py-1 text-[9px] text-slate-500">History retained</span></div></div></div></div>
			</div>
		</div>

		<div class="mt-24 grid items-center gap-10 lg:grid-cols-2 lg:gap-16">
			<div class="order-2 lg:order-1"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_22px_60px_rgba(50,58,70,0.09)]"><div class="flex flex-col items-center gap-2 sm:flex-row sm:justify-between">{#each [{ t: 'Conversation', s: 'Asha M.' }, { t: 'Enquiry', s: 'Website' }, { t: 'Quotation', s: 'QT-2041' }, { t: 'Booking / Order', s: 'GFA-BK-128' }, { t: 'Payment', s: 'Reported' }] as item, index (item.t)}<div class="w-full rounded-xl border border-slate-200 bg-slate-50/60 p-3 text-center sm:w-auto sm:flex-1"><div class="text-[9px] font-semibold text-slate-700">{item.t}</div><div class="mt-0.5 text-[8px] text-slate-400">{item.s}</div></div>{#if index < 4}<span class="rotate-90 text-slate-300 sm:rotate-0">→</span>{/if}{/each}</div><div class="mt-5 rounded-xl border border-dashed border-brand-200 bg-brand-50/60 p-3 text-center text-[10px] font-medium text-brand-700">Transaction context can arrive from your existing website, CMS or business software.</div></div></div>
			<div class="order-1 lg:order-2"><span class="feature-number">02 · Transaction infrastructure</span><h3 class="feature-title">Keep conversations connected to what customers are buying.</h3><p class="feature-copy">Connect accepts transaction context from integrations. Tours, products, rooms, services and packages can stay where you manage them today.</p><p class="mt-5 inline-flex rounded-full bg-success/10 px-3 py-1.5 text-[10px] font-semibold text-success">No catalog migration required</p></div>
		</div>

		<div class="mt-24 overflow-hidden rounded-[24px] border border-brand-200 bg-[#0e335d] text-white shadow-[0_35px_90px_rgba(14,51,93,0.20)]">
			<div class="grid items-center gap-10 p-6 sm:p-9 lg:grid-cols-[0.8fr_1.2fr] lg:p-12">
				<div><span class="text-[10px] font-bold tracking-[0.17em] text-blue-200 uppercase">03 · Payment infrastructure</span><h3 class="mt-4 text-3xl leading-tight font-bold tracking-[-0.035em] text-white">Payment requests that don’t end in a dead end.</h3><p class="mt-4 text-sm leading-7 text-blue-100/75">Tell the customer how to pay, capture their report, require verification, update the transaction and notify them—all without pretending a button proves money arrived.</p></div>
				<div class="rounded-2xl border border-white/15 bg-white p-5 text-slate-700 shadow-2xl"><div class="flex items-start justify-between gap-3"><div><p class="text-[9px] font-bold tracking-wider text-slate-400 uppercase">Payment requested</p><p class="mt-1 text-2xl font-bold text-slate-900">TZS 850,000</p><p class="mt-1 text-[10px] text-slate-400">M-Pesa · GFA-BK-2026-00128</p></div><span class="rounded-full bg-warning/10 px-2.5 py-1 text-[9px] font-semibold text-[#a9780c]">Awaiting verification</span></div><div class="mt-5 grid gap-2 sm:grid-cols-5">{#each [{ t: 'Requested', s: 'How to pay', c: 'done' }, { t: '“I have paid”', s: 'Customer report', c: 'done' }, { t: 'Verify', s: 'Staff action', c: 'active' }, { t: 'Booking updated', s: 'Domain service', c: 'later' }, { t: 'Customer notified', s: 'WhatsApp', c: 'later' }] as item, index (item.t)}<div class="rounded-xl border p-3 {item.c === 'done' ? 'border-success/20 bg-success/5' : item.c === 'active' ? 'border-warning/30 bg-warning/5' : 'border-slate-200 bg-slate-50'}"><span class="text-[8px] font-bold {item.c === 'done' ? 'text-success' : item.c === 'active' ? 'text-[#a9780c]' : 'text-slate-300'}">0{index + 1}</span><div class="mt-5 text-[9px] font-semibold text-slate-700">{item.t}</div><div class="mt-0.5 text-[8px] text-slate-400">{item.s}</div></div>{/each}</div></div>
			</div>
		</div>

		<div class="mt-24 grid items-center gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:gap-16">
			<div><span class="feature-number">04 · Team operations</span><h3 class="feature-title">One customer conversation. The right people around it.</h3><p class="feature-copy">Assignment, presence, roles and payment permissions make ownership visible without turning your business number into a shared password.</p><ul class="mt-5 space-y-1">{@render check('Conversation assignment and live presence')}{@render check('Private and assigned-only visibility')}{@render check('Role-based operational access')}{@render check('Dedicated payment verification permission')}</ul></div>
			<div class="grid gap-3 sm:grid-cols-3">{#each [{ initials: 'RJ', name: 'Robert', role: 'Manager', open: '4 open', detail: '12 replies today', tone: 'brand' }, { initials: 'NM', name: 'Neema', role: 'Agent', open: '2 open', detail: '8 replies today', tone: 'purple' }, { initials: 'FI', name: 'Finance', role: 'Custom role', open: '3 payments', detail: 'Awaiting verification', tone: 'warn' }] as member (member.name)}<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_16px_40px_rgba(50,58,70,0.07)]"><span class="flex size-10 items-center justify-center rounded-full text-[11px] font-bold {member.tone === 'brand' ? 'bg-brand-50 text-brand-600' : member.tone === 'purple' ? 'bg-purple/10 text-purple' : 'bg-warning/15 text-[#a9780c]'}">{member.initials}</span><h4 class="mt-5 text-sm font-semibold text-slate-800">{member.name}</h4><p class="text-[10px] text-slate-400">{member.role}</p><div class="mt-5 border-t border-slate-100 pt-4"><p class="text-xl font-bold text-slate-900">{member.open}</p><p class="mt-1 text-[10px] text-slate-400">{member.detail}</p></div></div>{/each}</div>
		</div>
	</div>
</section>

<section class="border-b border-slate-100 bg-[#0a203a] text-white">
	<div class="mx-auto max-w-[1240px] px-4 py-20 sm:px-6 lg:px-10 lg:py-24">
		<div class="max-w-2xl"><p class="text-[10px] font-bold tracking-[0.18em] text-blue-200 uppercase">Customer journey</p><h2 class="mt-3 text-3xl font-bold tracking-[-0.035em] text-white sm:text-4xl">From first message to confirmed customer.</h2></div>
		<div class="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-8">{#each [{ n: '01', t: 'WhatsApp message' }, { n: '02', t: 'Enquiry' }, { n: '03', t: 'Quotation' }, { n: '04', t: 'Payment request' }, { n: '05', t: '“I have paid”' }, { n: '06', t: 'Verification' }, { n: '07', t: 'Booking confirmed' }, { n: '08', t: 'Customer notified' }] as item (item.n)}<div class="relative rounded-xl border border-white/10 bg-white/5 p-3.5 backdrop-blur"><span class="text-[8px] font-bold text-blue-300">{item.n}</span><p class="mt-6 text-[10px] leading-4 font-semibold text-white/85">{item.t}</p></div>{/each}</div>
	</div>
</section>
